author: eccentric_nz
description: A Dynmap add-on to show TARDIS locations
main: me.eccentric_nz.dynmaptardis.DynmapTARDIS
name: Dynmap-TARDIS
load: POSTWORLD
version: 1.3.1
api-version: 1.13
website: http://dev.bukkit.org/bukkit-plugins/tardis
dev-url: http://dev.bukkit.org/bukkit-plugins/tardis
url: http://dev.bukkit.org/bukkit-plugins/tardis
depend: [dynmap,TARDIS]
